### ISSUE TITLE
Add versioning, visible in the UI

### ISSUE THREAD

**Issue by timjackson** [boogiespook/rti#17]
As a RTI assessor, I would like to see the version of the deployed application which I am using, so that I can check whether it is the latest version or not.

A simple incrementing number would be sufficient, for example displayed in the footer of the UI.
This could also be saved in the database when submitting an assessment, so that it's possible to backtrack to which version of the application was used for the assessment (potentially solving issue #12 )

**Comment by boogiespook** [comment]
Version number added in the header.
