### ISSUE TITLE
analyticstracking.php missing

### ISSUE THREAD

**Issue by timjackson** [boogiespook/rti#9]
Current master is broken due to lack of analyticstracking.php

Warning: include_once(analyticstracking.php): failed to open stream: No such file or directory in /path/to/index.php on line 105 Warning: include_once(): Failed opening 'analyticstracking.php' for inclusion (include_path='whatever') in /path/to/index.php on line 105

**Comment by boogiespook** [comment]
Thanks Tim - now uploaded.
